# Basic Information 
title: Ilham Sidik
position: Software Developer & Research Assistant
affiliation: Universitas Gadjah Mada
email: ilhamsidik98@mail.ugm.ac.id

# Links 
google_scholar: https://scholar.google.com/citations?hl=en&user=lT8tgboAAAAJ
github_link: https://github.com/ilhamsidik98
linkedin: https://www.linkedin.com/in/hamdik/
facebook: https://www.facebook.com/sagoham
instagram: https://www.instagram.com/ilham.sidik98/

# Images 
avatar: ./assets/img/profpic2.jpg
favicon: ./assets/img/favicon.ico
favicon_dark: ./assets/img/favicon.ico

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Serif" # or "Sans Serif"

# Remote Theme
remote_theme: yaoyao-liu/minimal-light

# Plugins
plugins:
  - jekyll-github-metadata

# Files to Exclude
exclude:
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/